In [2]:
import numpy as np

In [6]:
a = np.arange(6)

In [4]:
np.__version__

'1.23.5'

In [7]:
a

array([0, 1, 2, 3, 4, 5])

In [20]:
x = a[np.newaxis, :]

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [17]:
x

array([[0, 1, 2, 3, 4, 5]])

In [22]:
a.shape

(6,)

In [ ]:
# 